name: Flask Model Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Flask App and Deploy to Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key to SSH agent
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-add -l  # List loaded keys (for debugging)

      - name: Remove Old Deployment on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /path/to/your/app/directory  # Change to your app's directory on the Droplet
            docker stop flask-app || true
            docker rm flask-app || true
            docker rmi flask-app-image || true
            rm -rf *

      - name: Copy Application Files to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./*
          target: /path/to/your/app/directory  # Change to your app's directory on the Droplet

      - name: Build Flask App Docker Image on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /path/to/your/app/directory  # Change to your app's directory on the Droplet
            docker build -t flask-app-image .

      - name: Run Flask App Container with Gunicorn on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /path/to/your/app/directory  # Change to your app's directory on the Droplet
            docker run -d -v shared_data:/path/in/container --network my-network -p 5000:5000 --name flask-app flask-app-image gunicorn -w 4 -b 0.0.0.0:5000 app:app
