name: Flask Model Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Flask App and Deploy to Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key to SSH agent
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-add -l  # List loaded keys (for debugging)

      - name: Remove Old Deployment on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /tmp/ai-trading  # Change to the directory where your app will reside
            echo "Current directory: $(pwd)"
            ls -la
            docker stop flask-app || true
            docker rm flask-app || true
            docker rmi flask-app-image || true
            rm -rf *

      - name: Copy Application Files to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ./*
          target: /tmp/ai-trading

      - name: Build and Run Docker Image on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd /tmp/ai-trading
            docker build -t flask-app-image .
            docker run -v shared_data:/path/in/container -d --name flask-app --network my-network -p 5000:5000 flask-app-image
